### ISSUE TITLE
Fail to handle rotated samples?

### ISSUE THREAD

**Issue by phcerdan** [PerkLab/SlicerFreeSurfer#17]
Here is the initial mri from the free dataset: https://openneuro.org/datasets/ds004776/versions/1.0.0

https://s3.amazonaws.com/openneuro.org/ds004776/sub-01/anat/sub-01_T1w.nii.gz?versionId=lob8sYgfY.jRec5aLib_K73v_.NBAeQB

Here is the mrprage.nii.gz file from the pipeline (input grayscale volume):
[mprage.nii.gz.zip](https://github.com/PerkLab/SlicerFreeSurfer/files/13053617/mprage.nii.gz.zip)

Here is the lh.pial (for example) after running infant_recon_all: 
[lh.pial.zip](https://github.com/PerkLab/SlicerFreeSurfer/files/13053527/lh.pial.zip)

Direction Matrix:

![image](https://github.com/PerkLab/SlicerFreeSurfer/assets/3021667/a9581d0c-8866-4e4d-9ade-e299e3a97780)

Opening mprage.nii.gz as a regular volume and opening lh.pial as a Freesurfer model with mprage.nii.gz as reference:

![image](https://github.com/PerkLab/SlicerFreeSurfer/assets/3021667/ce92d564-9b1e-4fd9-b752-55da166fc5fa)

However, freeview reads and align the two files correctly.

![image](https://github.com/PerkLab/SlicerFreeSurfer/assets/3021667/ce24dfd9-38ea-42d7-ad0e-4ab27d73b2c8)

**Comment by Sunderlandkyl** [comment]
Thanks for reporting, I'm looking into it.

**Comment by phcerdan** [comment]
@Sunderlandkyl Any hints on where the problem lies?  Maybe I can be of help

**Comment by Sunderlandkyl** [comment]
Sure!

The current import process doesn't apply image orientation to the models, it only applies a translation to position the origin of the model at the correct location. This has worked for all of the sample data up to this point, since models in the other datasets don't seem to take into account the image orientation.

Applying image orientation to the models will fix the issue in this case, but breaks the other test cases.

Do you have any insight as to why this case is special or how we can distinguish between them?

**Comment by phcerdan** [comment]
> Applying image orientation to the models will fix the issue in this case, but breaks the other test cases.

It shouldn't break the other cases. The orientation matrix would become a ~~diagonal matrix~~ axis-aligned matrix for the non-rotated cases. And in case there is no scaling (spacing is 1mm), all the non-zero entries would be +-1.

Also, using this matrix, we can apply scaling/spacing (in freesurfer it seems the spacing is always 1mm though).

> Do you have any insight as to why this case is special or how we can distinguish between them?

Yeah, we should use the same machinery that Slicer uses, via ITK and or VTK, to read the metadata of the images and populate: Origin, Spacing and the Direction Matrix, and then instead of just applying a translation, apply the full transformation ( translation via Origin, scaling via Spacing, and rotation via Direction Matrix).

Freesurfer can show this information with mris_info and mri_info (voxel to ras matrix). But not sure how or in what format is that metadata stored in the mgz and the surface files.

**Comment by Sunderlandkyl** [comment]
In the examples from:
https://surfer.nmr.mgh.harvard.edu/pub/data/tutorial_data/long-tutorial/OAS2_0121/

This is the IJK To RAS matrix of the image, which is not a diagonal matrix:
![image](https://github.com/PerkLab/SlicerFreeSurfer/assets/9222709/1f0fea75-428b-40ab-a1a2-d0210f6b48f0)

The surfaces are positioned correctly by only applying translation:
![image](https://github.com/PerkLab/SlicerFreeSurfer/assets/9222709/cddf0ce4-1ae4-46d7-aa59-1f709d261811)

Interestingly I also have some examples with images that have 0.7mm spacing, however the surfaces are already scaled correctly, and applying it would distort them.

It's clear that applying the orientation is required in the example that you provided, however I'm not aware of how to distinguish between the cases where it is required and the ones where it seemingly isn't required.

**Comment by phcerdan** [comment]
The cases where a rotation isn't required will be handled with no problems when the rotated cases are handled, so we don't have to distinguish between them a priori.

Pinging @lassoan, maybe he can provide more guidance on this topic for Slicer.

**Comment by phcerdan** [comment]
Not sure if freesurfer pipeline can handle rotated images like this one. I see `mris_fill` cuts a bit the image.  Maybe is not worth the effort.

But at least showing a big warning that this plugin don't show rotated images correctly when opening one.

**Comment by lassoan** [comment]
If Freesurfer can be used multiple ways and we cannot tell how to correctly interpret the results then we could add an option in Slicer's importer to choose between the two methods.

Once we confirm that all data can be imported correctly with one or the other method, but there is no method that can load all data sets, we can ask the Freesurfer community why these two methods are necessary and if there is a way to automatically determine which one to use.

**Comment by Sunderlandkyl** [comment]
Some additional information that I've found: https://neurostars.org/t/transform-freesurfer-mesh-coordinates-to-volume-coordinates/23693/4

This part of the discussion appears relevant as it is the approach that we have been using as well:
> You’re doing the same thing that HCP Pipelines and fMRIPrep have done, which is just applying the translation encoded in C_RAS. If the image is oblique, you can get a non-identity XYZ_RAS matrix, in which case this will fail.

This discussion looks promising for coming up with the correct transformation:
https://github.com/nipy/nibabel/discussions/1249

**Comment by Sunderlandkyl** [comment]
I've updated the loading mechanism for loading FreeSurfer surfaces, so they should now be loaded in the correct position/orientation.
Now, we use NiBabel internally for loading the surfaces, rather than the old C++ implementations.

As a bonus, we no longer need to specify a reference volume when loading a surface, since NiBabel can read the orientation information stored in the surface file footer.

These changes should be available in the nightly preview build starting tomorrow.

**Comment by lassoan** [comment]
Awesome, very nice work!

**Comment by phcerdan** [comment]
Tested and works, thanks! :100:
