### ISSUE TITLE
Linux/Mac build error

### ISSUE THREAD

**Issue by lassoan** [PerkLab/SlicerFreeSurfer#2]
There is a minor build error on linux and mac:
http://slicer.cdash.org/viewBuildError.php?buildid=1898890

.toUtf8() or .toUtf8().constData() should work

After the issue is fixed (and maybe after #1 is fixed, too) and the extension shows up correctly on the extension manager, it would be nice if could announce the feature on youtube+discourse. Thank you!

**Comment by Sunderlandkyl** [comment]
I think the build error should be fixed by: https://github.com/PerkLab/SlicerFreeSurfer/commit/280fc819faad9be3706b491b7937de7a29556454
