### ISSUE TITLE
Extension category

### ISSUE THREAD

**Issue by lassoan** [PerkLab/SlicerFreeSurfer#3]
Currently, the extension shows up in "Examples" category. It should be something like "Neuro", "Neuroimaging", "Brain imaging",... Maybe ask Sylvain and Jared if they have any preferred name. It should be a name that will be suitable to host the new modules that we'll develop for them.

**Comment by Sunderlandkyl** [comment]
Neuroimaging is the one that I used on the extension index, so I'll use that here for now and ask Sylvain and Jarrett if they have a better name.

**Comment by lassoan** [comment]
Interestingly, the extension shows up in the extension manager in "Examples" category.

It is very important to only use the final category name because once you publish an extension with a category name then it cannot be removed, that name will appear on the extension manager forever, even if there are no extensions in that category (this is a bug but it will not likely to be fixed anytime soon).

Neuroimaging looks good to me (it is similar to the "Cardiac" category name; so we are consistently use Latin names instead of English "Heart" and "Brain"). So, either use that, or keep it at Examples until we finalize a name with Sylvain/Jared.

**Comment by Sunderlandkyl** [comment]
I discussed the extension category with Jarrett, and Neuroimaging was fine.
After Updating the CMake in this repo (https://github.com/PerkLab/SlicerFreeSurfer/commit/9a2bdd50c0fa1eaa99d33cd9a09faae97bf77a9c), the extension now appears in the correct category.
